package com.oxy.s3m.notification.model.customer;

import com.oxy.s3m.notification.model.categories.Categories;

// Generated Sep 18, 2017 11:09:55 PM by Hibernate Tools 5.2.3.Final

/**
 * SellerInterests generated by hbm2java
 */
public class CustomerInterests implements java.io.Serializable {

	private Integer id;
	private MasterArea masterArea;
	private Categories categories;
	

	private int sellerId;
	
	
	public Categories getCategories() {
		return categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public CustomerInterests() {
	}

	public CustomerInterests(MasterArea masterArea, int sellerId) {
		this.masterArea = masterArea;
		this.sellerId = sellerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MasterArea getMasterArea() {
		return this.masterArea;
	}

	public void setMasterArea(MasterArea masterArea) {
		this.masterArea = masterArea;
	}

	public int getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(int sellerId) {
		this.sellerId = sellerId;
	}

}
