package com.oxy.s3m.notification.model.customer;
// Generated Sep 18, 2017 11:09:55 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MasterArea generated by hbm2java
 */
public class MasterArea implements java.io.Serializable {

	private Integer id;
	private String area;
	private String city;
	private String state;
	private String country;
	private Integer mainAreaId;
	private Set<CustomerInterests> sellerInterestses = new HashSet<CustomerInterests>(0);

	public MasterArea() {
	}

	public MasterArea(String country) {
		this.country = country;
	}

	public MasterArea(String area, String city, String state, String country, Integer mainAreaId,
			Set<CustomerInterests> sellerInterestses) {
		this.area = area;
		this.city = city;
		this.state = state;
		this.country = country;
		this.mainAreaId = mainAreaId;
		this.sellerInterestses = sellerInterestses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getMainAreaId() {
		return this.mainAreaId;
	}

	public void setMainAreaId(Integer mainAreaId) {
		this.mainAreaId = mainAreaId;
	}

	public Set<CustomerInterests> getSellerInterestses() {
		return this.sellerInterestses;
	}

	public void setSellerInterestses(Set<CustomerInterests> sellerInterestses) {
		this.sellerInterestses = sellerInterestses;
	}

}
