package com.oxy.s3m.notification.beans.customer;
// Generated Sep 15, 2017 4:52:02 PM by Hibernate Tools 5.2.3.Final

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	/*private Integer msgId;
	private Notification notification;*/
	private String msgTxt;

	public Message() {
	}

	public Message(Notification notification, String msgTxt) {
		//this.notification = notification;
		this.msgTxt = msgTxt;
	}

	/*public Integer getMsgId() {
		return this.msgId;
	}

	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}
*/
	public String getMsgTxt() {
		return this.msgTxt;
	}

	public void setMsgTxt(String msgTxt) {
		this.msgTxt = msgTxt;
	}

}
