package com.oxy.s3m.notification.beans.customer;
// Generated Sep 15, 2017 4:52:02 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	//private Integer notificationId;
	//private Integer sellerId;
	private String notificationTitle;
//	private Date notificationStartdate;
	private Date notificationEnddate;
	//private String status;
	//private int catId;
	private Message messages;

	public Notification() {
	}

	public Notification(String notificationTitle, Date notificationStartdate, Date notificationEnddate, int catId) {
		this.notificationTitle = notificationTitle;
		//this.notificationStartdate = notificationStartdate;
		this.notificationEnddate = notificationEnddate;
		//this.catId = catId;
	}

	public Notification(Integer sellerId, String notificationTitle, Date notificationStartdate,
			Date notificationEnddate, String status, int catId, Message messages) {
		//this.sellerId = sellerId;
		this.notificationTitle = notificationTitle;
		//this.notificationStartdate = notificationStartdate;
		this.notificationEnddate = notificationEnddate;
		//this.status = status;
		//this.catId = catId;
		this.messages = messages;
	}

	/*public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	public Integer getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Integer sellerId) {
		this.sellerId = sellerId;
	}
*/
	public String getNotificationTitle() {
		return this.notificationTitle;
	}

	public void setNotificationTitle(String notificationTitle) {
		this.notificationTitle = notificationTitle;
	}

	/*public Date getNotificationStartdate() {
		return this.notificationStartdate;
	}

	public void setNotificationStartdate(Date notificationStartdate) {
		this.notificationStartdate = notificationStartdate;
	}
*/
	public Date getNotificationEnddate() {
		return this.notificationEnddate;
	}

	public void setNotificationEnddate(Date notificationEnddate) {
		this.notificationEnddate = notificationEnddate;
	}

/*	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getCatId() {
		return this.catId;
	}

	public void setCatId(int catId) {
		this.catId = catId;
	}
*/
	public Message getMessages() {
		return this.messages;
	}

	public void setMessages(Message msg) {
		this.messages = msg;
	}

}
